### ISSUE TITLE
PyPi version is still 1.4

### ISSUE THREAD

**Issue by adhawkins** [KenKundert/shlib#2]
The version on PyPi is still showing as 1.4. This prevented repology from warning me that there was an updated version so that I could package it for Alpine. Fortunately, I spotted it from the release announcement from GitHub.

**Comment by KenKundert** [comment]
Thanks Andy.  And sorry about that.  I have pushed the latest version to pypi.

**Comment by adhawkins** [comment]
No worries, thanks for sorting it!
